Controllers/CitizenController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using EnviroC.Models;
using EnviroC.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace EnviroC.Controllers
{
    public class CitizenController : Controller
    {
        private IErrandsRepository repository;


        public CitizenController(IErrandsRepository repo)
        {
            repository = repo;

        }
        public ViewResult Index()
        {
            ViewBag.Title = "Småstads kommun";
            Errand errand = new Errand();

            // Deserialize the saved Json object
            try
            {
                  errand = JsonConvert.DeserializeObject<Errand>(TempData["eTemp"].ToString());
            }
            catch
            {
                Console.WriteLine("Deserialization failed");
            }

            // Uses a view from the Home folder.
            return View("../Home/Index", errand);
        }
        public ViewResult Services()
        {
            ViewBag.Title = "Småstads kommun - Tjänster";
            return View();
        }
        public ViewResult FAQ()
        {
            ViewBag.Title = "Småstads kommun - FAQ";
            return View();
        }
        public ViewResult Contact()
        {
            ViewBag.Title = "Småstads kommun - Kontakt";
            return View();
        }
        public ViewResult Validate(Errand errand)
        {
            ViewBag.Title = "Småstads kommun - Bekräfta";


            // Serialize the Errand object, turning it into a JSON string. This is done because TempData only allows simple data types.
            string eAsJason = JsonConvert.SerializeObject(errand, Formatting.Indented);
            TempData["eTemp"] = eAsJason;

            return View(errand);
        }
        public ViewResult Thanks()
        {
            ViewBag.Title = "Småstads kommun - Rapportera brott";
            Errand errand = new Errand();
            errand.Pictures = new Collection<Picture>();

            // Deserialize the saved Json object
            try
            {
                errand = JsonConvert.DeserializeObject<Errand>(TempData["eTemp"].ToString());
            }
            catch
            {
                Console.WriteLine("Deserialization failed");

            }

            repository.SaveErrand(errand);

            // The object is also sent to Thanks.cshtml so that Model.RefNumber can be displayed
            return View(errand);
        }
    }
}

Views/Shared/_BasicLayout.cshtml
<!DOCTYPE html>


<html xml:lang="sv" lang="sv">
<head>
    <meta charset="UTF-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="/css/style.css" />
    <!--These three scripts make it so that wrong input in the forms is not validated'-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
</head>

<body>
    <div id="wrapper">
        <header id="logo">
            <h1>Småstad</h1>
            <p>Kommunen där vi bryr oss om varandra</p>
        </header><!-- End header -->

        @RenderBody()
                
    </div><!-- End Wrapper -->


</body>
</html>

Views/Shared/_LoginFalseLayout.cshtml
@{
    Layout = "_BasicLayout";
}

<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
        <li><a asp-controller="Citizen" asp-action="Services">Tjänster</a></li>
        <li><a asp-controller="Citizen" asp-action="FAQ">FAQ</a></li>
        <li><a asp-controller="Citizen" asp-action="Contact">Kontakt</a></li>
        <li class="right"><a class="login" asp-controller="Home" asp-action="Login">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <div>
        @RenderBody()

    </div>
    <aside id="sideColumn">
        <img src="~/images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="~/images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="~/images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="~/images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="~/images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="~/images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="~/images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="~/images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->
    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Views/Shared/_LoginTrueLayout_Coordinator.cshtml
@{
    Layout = "_BasicLayout";
}


<nav>
    <ul>
        <li><a class="reports" asp-controller="Coordinator" asp-action="LoggedIn_Coordinator">Start(Ärenden)</a></li>

        <li><a class="reportAdd" asp-controller="Coordinator" asp-action="LoggedIn_ReportCrime_Coordinator">Rapportera brott</a></li>
        <li class="right"><a class="logout" asp-controller="Account" asp-action="Logout">Logga ut</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">

    @RenderBody()
    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>

</div><!-- End Content -->

Views/Shared/_LoginTrueLayout_Investigator.cshtml
@{
    Layout = "_BasicLayout";
}


<nav>
    <ul>
        <li><a class="reports" asp-controller="Investigator" asp-action="LoggedIn_Investigator">Start(Ärenden)</a></li>
        <li class="right"><a class="logout" asp-controller="Account" asp-action="Logout">Logga ut</a></li>
    </ul>
</nav><!-- End Nav -->
<div id="content">

    @RenderBody()
    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>

</div><!-- End Content -->

Views/Shared/_LoginTrueLayout_Manager.cshtml
@{
    Layout = "_BasicLayout";
}


<nav>
    <ul>
        <li><a class="reports" asp-controller="Manager" asp-action="LoggedIn_Manager">Start(Ärenden)</a></li>
        <li class="right"><a class="logout" asp-controller="Account" asp-action="Logout">Logga ut</a></li>
    </ul>
</nav><!-- End Nav -->
<div id="content">

    @RenderBody()
    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>

</div><!-- End Content -->